version: "3"
services:
  app:
    container_name: "gobel-admin-client-example"
    build:
        context: "./app"
        dockerfile: "Dockerfile.ci"
    ports:
      - "8081:8081"
    command: ./gobel-admin-client-example