settings:
  legacy:
    force: true
    interval: 0s
schema:
- name: gobel-admin-client-example
  path: .
  commands:
    build:
      status: true
      method: go build -o /gobel-admin-client-example
    run:
      status: true
      method: /gobel-admin-client-example
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
